name: ✨ 功能请求
description: 提议新功能或改进
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        感谢你的建议！请详细描述你的想法。

  - type: checkboxes
    id: pre-check
    attributes:
      label: 提交前检查
      options:
        - label: 我已搜索[Issues](https://github.com/vjsplus-j/vjs-ui/issues)和[Discussions](https://github.com/vjsplus-j/vjs-ui/discussions)，确认这不是重复请求
          required: true
        - label: 这个功能与VJS-UI的定位相符
          required: true

  - type: textarea
    id: problem
    attributes:
      label: 问题描述
      description: 这个功能解决了什么问题？
      placeholder: 我经常需要...，但是目前...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: 期望的解决方案
      description: 你期望如何解决这个问题？
      placeholder: 我希望VJS-UI能够...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 替代方案
      description: 你考虑过哪些其他解决方案？
      placeholder: 我也考虑过...

  - type: textarea
    id: use-case
    attributes:
      label: 使用场景
      description: 请描述具体的使用场景
      placeholder: |
        场景1: 在后台管理系统中...
        场景2: 在数据可视化页面...
    validations:
      required: true

  - type: textarea
    id: api-design
    attributes:
      label: API设计（可选）
      description: 如果有想法，请描述你期望的API
      placeholder: |
        ```typescript
        // 示例代码
        import { newFeature } from '@vjs-ui/vue'
        ```

  - type: textarea
    id: additional
    attributes:
      label: 补充信息
      description: 其他任何相关信息、截图、链接等
